import type { Items } from "./types";

export const folderItems: Items[] = [
  {
    name: "Files",
    owner: "Adam",
    date: "Jul 3, 2025",
    isFolder: true,
    extension: "",
    size: "",
    items: "4",
    id: 1,
  },
  {
    name: "Documents",
    owner: "Adam",
    date: "Jul 3, 2025",
    isFolder: true,
    extension: "",
    size: "",
    items: "12",
    id: 2,
  },
  {
    name: "Misc",
    owner: "Adam",
    date: "Jul 4, 2025",
    isFolder: true,
    extension: "",
    size: "",
    items: "5",
    id: 3,
  },
  {
    name: "Other",
    owner: "Adam",
    date: "Jul 4, 2025",
    isFolder: true,
    extension: "",
    size: "",
    items: "2",
    id: 4,
  },
  {
    name: "More",
    owner: "Adam",
    date: "Jul 4, 2025",
    isFolder: true,
    extension: "",
    size: "",
    items: "5",
    id: 5,
  },
];
export const fileItems: Items[] = [
  {
    name: "Presentation",
    owner: "Adam",
    date: "Jul 4, 2025",
    isFolder: false,
    extension: "pdf",
    size: "56 KB",
    id: 1,
  },
  {
    name: "Word",
    owner: "Adam",
    date: "Jul 4, 2025",
    isFolder: false,
    extension: "word",
    size: "56 MB",
    id: 2,
  },
  {
    name: "Excel",
    owner: "Adam",
    date: "Jul 4, 2025",
    isFolder: false,
    extension: "xls",
    size: "24 MB",
    id: 3,
  },
  {
    name: "Adjust",
    owner: "Adam",
    date: "Jul 4, 2025",
    isFolder: false,
    extension: "xls",
    size: "442 KB",
    id: 4,
  },
  {
    name: "Difference",
    owner: "Adam",
    date: "Jul 4, 2025",
    isFolder: false,
    extension: "pdf",
    size: "46 KB",
    id: 5,
  },
];
